### ISSUE TITLE
Chatter issue on formview sales order

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#103]
Since last friday the chatter on the sale.order formview is no longer positioned on the right side of the screen, but below the orderlines. Chatter should be on the right.

![image](https://github.com/onesteinbv/addons-container/assets/30256071/225798c8-3f42-4b84-92ec-55694f771496)

**Comment by bvanjeelharia** [comment]
@ThijsvOers , you just need to zoom out to see the chatter on the right, once you zoom in you see the chatter on the bottom

**Comment by ThijsvOers** [comment]
Might be related to the fact that I installed the starter container. In other containers I do not have this error

**Comment by ThijsvOers** [comment]
I will close the issue for now
