### ISSUE TITLE
Reconciliation models payment tolerance problem with reconcile_oca

### ISSUE THREAD

**Issue by yung-wang** [onesteinbv/addons-container#105]
Hi @bvanjeelharia,

As sproken and showed, we encounter a problem with auto validation of invoices when we also use the Payment Tolerance?

Enterprise (account.reconcile.model)
![image](https://github.com/onesteinbv/addons-container/assets/30628967/7f8148a2-2c2e-497d-9dae-a54c19983913)

Curq
![image](https://github.com/onesteinbv/addons-container/assets/30628967/a6b147e0-4205-4828-ac7a-5290848a3078)

I created in both environment an customer invoice. The customer pays but with 1 cent difference.

Enterprise it links the invoice and creates an extra line for the discount.
![image](https://github.com/onesteinbv/addons-container/assets/30628967/42ee2103-6bf9-4190-ae81-051eb45c8488)

In Curq there will be only 1 line for the full amount for the discount.
![image](https://github.com/onesteinbv/addons-container/assets/30628967/47e87db8-da2e-4c7b-b1b9-d835e0131cd4)

Im testing in this environment:
https://finance02.curq.k8s.onestein.eu/web

**Comment by ThijsvOers** [comment]
@yung-wang Tested in this instance and issue seems resolved to me (I think Anjeel worked on this issue, but  he did not add his remarks on this task). Can we close the task here?

![image](https://github.com/onesteinbv/addons-container/assets/30256071/f68154e6-9058-42c1-b2bc-0e8daa0f1f41)

**Comment by bvanjeelharia** [comment]
Yes, I resolved the issue @ThijsvOers

**Comment by yung-wang** [comment]
is fixed
