### ISSUE TITLE
RGS: split rgs type from company type

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#11]
We want to manage 3 types of companies: ez,zzp,bv.
We want to manage 2 types (or levels?) of RGS accounts: basic,extended.
The actual idea (that could change in the future) is this:

- create all the accounts, regardless if they belong to basic or extended
- automatically set the extended accounts (that are not basis) to archived
- if an extended account is explicitly defined for the selected type of company, do not archive it

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/a8ed6c4b414204fbb0a12da09c0ae863ee195596

**Comment by astirpe** [comment]
@andreschenkels With commit https://github.com/onesteinbv/addons-container/commit/e58edbc9aa28543efcb742bab61b045f1a6cd9f6 I just removed the company type fields and replaced them with just one flag for the accounts deprecated. The idea is to install the entire chart of account anyway, and flag the deprecated accounts. This request came from @ThijsvOers and Joery

**Comment by ThijsvOers** [comment]
We will no longer make the difference between companies, will close this task
