### ISSUE TITLE
RGS: tax accounts for services

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#12]
At the moment, tax accounts for services are defined in RGS but not linked to any tax.
Taxes for services should be added into the account.tax.template and linked to RGS tax accounts, the same way as it was done with the standard Odoo coa for NL.
Fiscal position template should be updated accordingly.

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/0b619a4237b02442ad234f48765ae851c9f52ffd

**Comment by astirpe** [comment]
When creating products, the fields `Customer Taxes` and `Vendor Taxes` should be correctly configured, by selecting the right tax for services or goods, depending on the type of product.

However an automatic selection of the `Customer Taxes` and `Vendor Taxes` is provided by the OCA module `product_category_tax`, already included in the container package. This module allows to automatically configure the proper taxes based on the product category. **This should be explained to the end user**, to avoid configuration mistakes.

With https://github.com/onesteinbv/addons-container/commit/ee1525074ce36a94fdd44711ec30382e6461ee39 I just added the `product_category_tax` module in the dependencies of `l10n_nl_rgs_usability`

**Comment by ThijsvOers** [comment]
@astirpe Joery told me in our latest meeting that taxs for service are not to be specified for purchases. So we can remove all of these new taxes,

**Comment by ThijsvOers** [comment]
@astirpe since we added the tax scope to the lines in menu Taxes, this info is now shown twice (see screenhot). Maybe its better to change the manually added infirmation. Can I do that myself or is this to be done by you? In the example you will see the text 'diensten' and also (Diensten)
![image](https://github.com/onesteinbv/addons-container/assets/30256071/ef3d2bdb-570f-4e88-9a2c-0ec5b5d2edb4)

**Comment by ThijsvOers** [comment]
I add the bug label since the purchase service taxes should be removed

**Comment by astirpe** [comment]
@ThijsvOers I see the issue but what do you mean with "Maybe its better to change the manually added information" ?

**Comment by astirpe** [comment]
Purchase service taxes removed in https://github.com/onesteinbv/addons-container/commit/8d3dd0430174f640c847884bd6a5825bf10511ca

**Comment by ThijsvOers** [comment]
> @ThijsvOers I see the issue but what do you mean with "Maybe its better to change the manually added information" ?

@astirpe remove this text in BTW Naam (see screenshot)

![image](https://github.com/onesteinbv/addons-container/assets/30256071/a3e0210a-bbe4-42b3-83dc-c055fcb15bf9)

**Comment by astirpe** [comment]
Removed "diensten" from BTW Naam: https://github.com/onesteinbv/addons-container/commit/15fb123bf57387b8f4f74c33416cdf4caaa2292b

**Comment by ThijsvOers** [comment]
Tested and should work correct now
