### ISSUE TITLE
RGS: bank account not to be created automatically when creating banks

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#13]
When creating account journals of type == Bank, the Bank Account must be not created automatically. The Bank Account has to be selected from existing RGS accounts.

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/d575029a810653052673bc4f1b1ce8b4e1f59d8f

**Comment by astirpe** [comment]
Loading demo data fixed in https://github.com/onesteinbv/addons-container/commit/44750ae0e1e88254988832418bb12ee732b85fcd

**Comment by astirpe** [comment]
Proposal for improving usability:

- create a new module `l10n_nl_rgs_usability`
- add dependency to `l10n_nl_rgs` and `base_view_inheritance_extension`
- in form view of `account.journal`, on field `default_account_id` pass context `{"domain_account_journal_type": object.type}`
- in `account.account` add method `def name_search()` so that, in case `domain_account_journal_type` is defined, the standard domain is extended with: `args = [("code", "=ilike", company.bank_account_code_prefix + "%")] + args`

**Comment by astirpe** [comment]
Module for usability improvements added with https://github.com/onesteinbv/addons-container/commit/dfa1c0b4f322129b91de5914a5d5827a99cea6f0

**Comment by astirpe** [comment]
Same issue applies to account journals of type == Cash, this case is also fixed in https://github.com/onesteinbv/addons-container/commit/a356e06239650257ec59d370a3a157090daeb503

**Comment by andreschenkels** [comment]
@astirpe was this seen as an issue because I talked about this with Joery and you just need to create the bacnk account numbers at the correct place in the schema and add a reference code.

**Comment by astirpe** [comment]
@andreschenkels 

Odoo automatically creates accounts for banks when the user is creating a new bank journal. This is an issue because the the newly created account would be not from the RGS schema, which already contains a set of predefined accounts for banks. 

With this fix, the user is forced to select an existing bank account from RGS schema.

Let me know if you need extra clarifications.

**Comment by andreschenkels** [comment]
@astirpe I know there are some accounts defined in the RGS. But you could easily create accounts on the same place in the RGS schema. You're solution is valid. But maybe less user friendly.

**Comment by astirpe** [comment]
This solution is actually what it came out from the discussion with Joery last friday. But I agree with you that it could be made more user friendly by making it smarter.

**Comment by astirpe** [comment]
With PR https://github.com/onesteinbv/addons-container/pull/17 the bank account is automatically selected in case there is any bank account available. It's a small usability improvement.

The logic of creating new bank accounts is not yet implemented, but maybe it could be easily achieved by adding extra bank accounts directly in the csv file, as Joury explained during the last meeting.

**Comment by astirpe** [comment]
~As a reminder for me, set the bank account to active (not deprecated) after the creation of the bank.~

Edited: done in https://github.com/onesteinbv/addons-container/commit/6288b1e086e0ef062cf41503ca9a5febea7b9746

**Comment by ThijsvOers** [comment]
@astirpe When duplicating a bank journal the correct settings are now applied (new account, new reference code, correct default settings for short code and sequence). Is there someting else to be done?

**Comment by astirpe** [comment]
@ThijsvOers I think this issue can be closed, since it was tested multiple times. If needed we could reopen it later on.
