### ISSUE TITLE
RGS: Allowed journals, correct map to be configured

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#14]

**Comment by ThijsvOers** [comment]
All account in group 421 should have the Bank allowed, please add these

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/635ca68739d4a130ac82c84311fea6071f468192

**Comment by ThijsvOers** [comment]
@astirpe I have tested the flow with anglo saxon accounting and in order to make all the bookings please add the customer invoice journal to account 7001010
![image](https://github.com/onesteinbv/addons-container/assets/30256071/497be8fd-3f14-4c25-a227-2b898e0f6c96)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/10b56b3dc48bef399306417396eddcc98c0037aa

**Comment by ThijsvOers** [comment]
@astirpe I am reoping the issue since we will have more accounts to add. For starters can you add for account  1101050 'Bank'as alloed journal?

**Comment by ThijsvOers** [comment]
4210070 should also have the 'bank journal AND the customer invoice journal, 1101010 should have group 'Bank

**Comment by ThijsvOers** [comment]
1203050 should have bank groups added as well
1203010  should have bank groups added as well

**Comment by astirpe** [comment]
Allowed journals for 1101050, 4210070, 1101010, 1203050, 1203010 done in https://github.com/onesteinbv/addons-container/commit/6cb074da5c834b09030b8a20618c1eb56669e6db

**Comment by ThijsvOers** [comment]
@astirpe 
7008020 should have Bank as journal
7008010 should have customer invoice AND Bank as allowed journal

**Comment by astirpe** [comment]
Allowed journals for 7008020 and 7008010 done in https://github.com/onesteinbv/addons-container/commit/e54828d14aacbbdf9c150ed989928daafa27a3ec

**Comment by ThijsvOers** [comment]
I did a test for the basic flows (sales order invoice, purchase order vendor bill, bank payment, assets, misccellaiuos and did not got amy error regarding this task. I will close the task for now, we can always re-open it
