### ISSUE TITLE
Include OCA spreadsheet in Container

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#15]
In order to be able to configure dashboards, we would like to add the following module to the Curq standard setup. With this module the enduser can define their own dashbord in Excel

https://github.com/OCA/spreadsheet

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/a42f0bf3c1c16d1ac344e0815ab9ce2d21b5394a
