### ISSUE TITLE
RGS: check account types in V16

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#16]
Since account type functionality inV16 was completely changed compared to V15, we need to check that the account types are correctly set in V16.

**Comment by ThijsvOers** [comment]
I suspect we have only a couple of active accounts to chack, see screenshot. I will check with Joery
![download](https://github.com/onesteinbv/addons-container/assets/30256071/8d6759d9-f9bf-4f93-a8b6-6fef5230127d)

**Comment by ThijsvOers** [comment]
It; s done. i will close the task
