### ISSUE TITLE
RGS: translation of account names to english

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#18]
The translation of account names to english could be done based on the document in:

https://referentiegrootboekschema.nl/dataset-engelse-labels

In V16 the translation should be done in the `nl.po` file.

Notice: starting from Odoo V17 it seems it will be possible to include the english translation directly in the .csv file, that would be much easier to handle and to update once the RGS schema changes.

**Comment by ThijsvOers** [comment]
Do we really need this functionality? which of the user will need the translated accounts?

**Comment by astirpe** [comment]
@ThijsvOers I don't think it's needed for the time being, so you you agree and nobody else is complaining, I'm closing this issue
