### ISSUE TITLE
l10n_nl_rgs: non-RGS accounts

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#2]
This is the same as issue as https://github.com/onesteinbv/addons-container-accountancy/issues/2 that was posted in a repository that is now archived. I copy the issue also here, so that it will not be lost.

When installing `l10n_nl_rgs`, the chart of accounts of company "NL Company RGS" contains extra accounts that are not defined in RGS chart:

	1001011 Cash
	1002016 Bank Suspense Account
	1002017 Outstanding Receipts
	1002018 Outstanding Payments
	1002019 Bank
	1003011 Liquidity Transfer
	9990001 Cash Difference Loss
	9990002 Cash Difference Gain
	999999 Undistributed Profits/Losses

Those accounts are automatically created by Odoo. So it seems that the mapping of default accounts in [account_chart_template.xml](https://github.com/onesteinbv/addons-customer-fid/blob/15.0/l10n_nl_rgs/data/account_chart_template.xml#L8-L10) and [account_chart_template_post_data.xml](https://github.com/onesteinbv/addons-customer-fid/blob/15.0/l10n_nl_rgs/data/account_chart_template_post_data.xml#L5C66-L14) is still to be completed.

**Comment by andreschenkels** [comment]
Most number do exist in the scheme. 1001011 is also correct for Kas / Cash

I changed a lot of these numbers so they should be a lot better now.

**Comment by astirpe** [comment]
Thank you!

I just installed the module locally and here is the list of accounts that are still automatically created by Odoo.

```
1001011 Cash
1002012 Outstanding Receipts
1002013 Outstanding Payments
1002014 Bank
1003011 Liquidity Transfer
9990001 Cash Difference Loss
9990002 Cash Difference Gain
999999 Undistributed Profits/Losses
```

**Comment by astirpe** [comment]
"Outstanding Receipts" and "Outstanding Payments"  fixed in https://github.com/onesteinbv/addons-container/commit/e6eb30df5f6971cb36db16c61b095f49450500f2

**Comment by astirpe** [comment]
"Profit account" and "Loss account" fixed in https://github.com/onesteinbv/addons-container/commit/af29bef2c40c56cf32df3ddb3514ea3f1c627ed3 ("Loss account" definition still to be fixed)

**Comment by astirpe** [comment]
Recap of the accounts still without Referentiecode so far:

```
1001011 Cash
1002017 Bank
999997  Cash Difference Gain
999998  Cash Difference Loss
999999  Undistributed Profits/Losses
```

**Comment by ThijsvOers** [comment]
![image](https://github.com/onesteinbv/addons-container/assets/30256071/6ddbf591-b7a4-497f-9cbf-ba2f38933122)
for Kas

**Comment by astirpe** [comment]
"Kas" account fixed in https://github.com/onesteinbv/addons-container/commit/a356e06239650257ec59d370a3a157090daeb503

**Comment by astirpe** [comment]
Recap of the accounts still without Referentiecode so far:

```
999997  Cash Discount Gain
999998  Cash Discount Loss
999999  Undistributed Profits/Losses
```

**Comment by ThijsvOers** [comment]
8407010 gain 999997
8407011 loss 999998
0506010 for 9999999

**Comment by astirpe** [comment]
@ThijsvOers please check my comment https://github.com/onesteinbv/addons-container/issues/2#issuecomment-1667910842

In the comment I specified that the change I made had to be reviewed.
For example:

- account `8407010` is considered as a "cost" in the RGS, and therefore it's type is set to `expense`; however we are now putting it as "gain" (Cash Discount Gain) and I would expect its type as `Other Income` instead of `Expense`
- account `8407010` and `8407011` description are the same, should be different

Please also notice that I changed the accounts so that they now differ from the official RGS schema

**Comment by astirpe** [comment]
Cash Discount Gain and Cash Discount Loss  done in https://github.com/onesteinbv/addons-container/commit/510facecb291f61308ef5ea5a83c420ce15dd36b
Undistributed Profits/Losses done in https://github.com/onesteinbv/addons-container/commit/f034a860ca4364ff0cccd7a93e96e40a515cad42

**Comment by astirpe** [comment]
@ThijsvOers news regarding `8407010` and `8407011`?

**Comment by ThijsvOers** [comment]
@astirpe we have the correct accounts for both the cash accounts, this should be 4210070  for both (checked and advised by Joery)

**Comment by astirpe** [comment]
"Profit account" and "Loss account": https://github.com/onesteinbv/addons-container/commit/a02b99d4127e5116311ceaed73016acf29bd7d37

**Comment by ThijsvOers** [comment]
Checked and ok
