### ISSUE TITLE
Hide Cash basis

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#22]
Hide cash basis when NL invoice basis is True (on the settings menu)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-oca/commit/be1703e65a64b254227a5df9df11bda6984df182

**Comment by ThijsvOers** [comment]
Testes and ok

**Comment by ThijsvOers** [comment]
@astirpe I just saw that in the latest test db (with latest changes) the cash basis checkbox is visible again. I tested this with the 'onestein' user account (where the settings menu is visible)


![image](https://github.com/onesteinbv/addons-container/assets/30256071/70f9040f-9d36-4216-8f90-569aecb4b8ab)

**Comment by astirpe** [comment]
Opened an OCA PR https://github.com/OCA/l10n-netherlands/pull/402 to avoid that the fix will be overwritten again.
@ThijsvOers can you approve the OCA PR?

**Comment by astirpe** [comment]
Restored in https://github.com/onesteinbv/addons-oca/commit/da59d0b04ba6fbe5c77090fc22241da6f19b9561

**Comment by ThijsvOers** [comment]
Tested and ok
