### ISSUE TITLE
Add module account_chart_update to container

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#23]
https://github.com/OCA/account-financial-tools/tree/16.0/account_chart_update

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/e29cac945719362177a0a9d4a939c51ffabd83c5 (added to package but not auto-installed)

**Comment by ThijsvOers** [comment]
@astirpe I installed the module, but do not see the menu (update chart under the accounting setting menu). I changed the user setting as you explained yesterday, without result

**Comment by astirpe** [comment]
@ThijsvOers should be in Settings > Invoicing > Update Chart Template

**Comment by ThijsvOers** [comment]
@astirpe Module is instaleld and works, but I am not sure what will be updated based on which information. It looks like the Old Chart of account is compared to the RGS and the module wants to change the RGS according to the old data. This task is to be tested later I guess

**Comment by astirpe** [comment]
@ThijsvOers This is an OCA module that I never used, so I don't know much about it. But for what I understand from your message, looks like doesn't work properly. Maybe we could check it deeper when the other things will be settled down, since I don't think this module is a priority at the moment.

**Comment by astirpe** [comment]
Module added
