### ISSUE TITLE
Activate accounting settings

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#24]
Please set the following options under the accounting setting to True:
- analytic accounting
- invoice analysis

-

**Comment by astirpe** [comment]
Done:

- analytic accounting: https://github.com/onesteinbv/addons-container/commit/d85d6890c16b2069c5b9e4d4457292866d156a87
- invoice analysis: https://github.com/onesteinbv/addons-container/commit/7a5668c97385090c9414e615f1555b0f05c03f08

**Comment by ThijsvOers** [comment]
tested and ok
