### ISSUE TITLE
RGS: Delete 1101015 account

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#27]
@astirpe 
Please delete in the RGS the line with account number 1101015. This number does not exist in the official RGS schem and looks to be a copy of 1101010
![download](https://github.com/onesteinbv/addons-container/assets/30256071/4a112ce1-f331-4ae5-a4e3-586c2ae345a9)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/4d0b274a80dc32317fe80d9c0084f20eab81149b

**Comment by ThijsvOers** [comment]
Checked and ok
