### ISSUE TITLE
Missing group info on accounts

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#29]
![missing accounts](https://github.com/onesteinbv/addons-container/assets/30256071/7429227e-7a0f-4359-a9dc-e0dbb51b6456)
[Rekening (account.account) (6).xlsx](https://github.com/onesteinbv/addons-container/files/12464257/Rekening.account.account.6.xlsx)
See the file for missing groups

**Comment by ThijsvOers** [comment]
Account 1103180 has Group 1103000 Bram will add the details

**Comment by astirpe** [comment]
[Missing_groups_rgs.ods](https://github.com/onesteinbv/addons-container/files/12465874/Missing_groups_rgs.ods)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/4c051a813c26656df3064af7c395821e0cced68d and https://github.com/onesteinbv/addons-container/commit/f6b9e0ae618e6bede677d470eb4bd2c2beddf17c

**Comment by ThijsvOers** [comment]
Tested on the latest DB and now all accounts have Groups
