### ISSUE TITLE
Add journals to allowed

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#30]
After creating a new Bank this new journal needs to be added to the allowed journal section of all accounts that already has bank.
The same applies to customer invoices, vendor bills

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/fa88b2b620765641ce4421058a44fbd3c5b1bb69

**Comment by ThijsvOers** [comment]
Tested and ok

**Comment by ThijsvOers** [comment]
@bvanjeelharia : Anjeel, we need one restriction to this task: Banks should only be copied to accounts which are NOT of type 'cash and bank'. The logic behind this is that you can only assign one bank account to the related accountnumber. 

When you create Bank 2, the account for Bank 2 is not allowed for the account that is related to Bank 1. Let me know if you have questions
