### ISSUE TITLE
Auto-select dutch language when creating a new instance of container

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#33]
Auto-select dutch language when creating a new instance of container:

1. install dutch language
2. set dutch language as default language for new users

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/c50b9e925670f1b4dc8ae594388b10557bab88ae

**Comment by ThijsvOers** [comment]
@astirpe I tested this and this works. Is there a possibility to activate the English language as well? or can you activate only one language in the initial setup?

**Comment by astirpe** [comment]
@ThijsvOers it's possible to activate also English, I will do :+1:

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/f98ca4961980ef5b34cbbf77310217a51256f293

**Comment by ThijsvOers** [comment]
Tested and OK, both languages are activated and Dutch is the default active one
