### ISSUE TITLE
VAT included not a tax label now

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#34]
In the new standard the VAT labels for tax included are not available. Implementing this will mean that we get quit a few new lines,. Nte: we do NOT need to differentiate for purchase VAT accounts goods and services

Sales:
- VAT included 21 for goods
- VAT included 21 for services
- VAT included 9 for goods
- VAT included 9 for services
Purchase:
- VAT included 21
- VAT included 9

**Comment by astirpe** [comment]
@ThijsvOers I don't understand this issue, for what I see all the taxes have the label. I'm maybe missing something.  Can you clarify?

**Comment by ThijsvOers** [comment]
@astirpe checked the latest update and I thin everything is correct now for the VAT labels. I will close the task

**Comment by ThijsvOers** [comment]
@astirpe I have just installed the lastest version, what is missing are the VAT included records for sales. In slaes you also can sell products VAT included. So we do need the following 4 extra records:
VAT included 21 for goods
VAT included 21 for services
VAT included 9 for goods
VAT included 9 for services

in the Joybots environment we created the missing lines manually:
![image](https://github.com/onesteinbv/addons-container/assets/30256071/7bd0bca0-f89f-4de2-8c2a-080245ffb3f6)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/ce039198b0e766e091711d7601bcfb0dd108856a

**Comment by ThijsvOers** [comment]
Tested with the latest commits and ok
