### ISSUE TITLE
Fiscal years and date ranges

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#35]
In order to work easily with fiscal reports we want default fiscal years (starring 2022 until 2026) and default date ranges (years) for these years

**Comment by astirpe** [comment]
As a reminder for me: evaluate porting of module https://github.com/onesteinbv/addons-generic/tree/13.0/account_period_auto_create to V16

**Comment by astirpe** [comment]
Module **_account_period_auto_create_** ported to V16 with extra implementations.
Now the module is automatically generating date ranges for:

- months
- quarters
- years

There is a cron job that is periodically creating new date ranges in case needed.

In addition to that, I also added the OCA module **_account_fiscal_year_auto_create_**. The module is supposed to automatically create standard Odoo fiscal years (not date ranges).
I didn't test this module, so probably there's some configuration to be done, not sure.


@ThijsvOers do you have the possibility to check if both modules are needed, I guess I will have feedback on those modules?

**Comment by ThijsvOers** [comment]
@astirpe maybe there was a fix in another task, but as far as I can see it, everything looks ok now:
- Only taxscope field filled in for Sales, no differentiation for Purchase, VAT included labels. I will close the task

**Comment by ThijsvOers** [comment]
@astirpe I wrote my comment on the wrong issue, i will have to look into this task

**Comment by astirpe** [comment]
@ThijsvOers there's an option to delete your comment, if you want

**Comment by ThijsvOers** [comment]
@astirpe I think I know how the module works. If I wuld create a default set of date ranges and fiscal periodes, would you be able to enter this data in the setup? I have done some testing and can create Years, quarters etc. We will have to check which ranges are needed and what prefixes are requested.

**Comment by astirpe** [comment]
Added monthly and quarterly for current year  in https://github.com/onesteinbv/addons-generic/commit/97552cf3987a6737339b22ee5b4ad338b4676976

**Comment by ThijsvOers** [comment]
@astirpe tested and ok

**Comment by ThijsvOers** [comment]
@bvanjeelharia I have created a second company in my test environment. IN that second company the date ranges are created once a planned action is run (auto create accounting period and auto generate date ranges). The issue is that only year 2027 is created in this company. I think the other years are not created since they were already created for the first company.

Months and quarters are created for previous years, so this remark concerns the creation of the Years (Y)

**Comment by ThijsvOers** [comment]
Checked and ok, keep in mind to run the cronjobs to create the date ranges and fiscal years
