### ISSUE TITLE
Add tax scope to all vat Sales records

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#36]
PLease add the correct goods or services tax scop to the Sales VAT , see the screenshots for the correct info

![tax scope](https://github.com/onesteinbv/addons-container/assets/30256071/dfa85fca-2dc8-40a2-bd3c-6e17779a05d3)

**Comment by astirpe** [comment]
Added tax scope to sale taxes in https://github.com/onesteinbv/addons-container/commit/62f1753b2f0178a4ef4f62ebaf949f174f70db5d

**Comment by ThijsvOers** [comment]
Tested and ok

**Comment by ThijsvOers** [comment]
Jovain/Joybots checked
