### ISSUE TITLE
Correct configuration of accounts for the reconciliation settings

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#38]
Some accounts do need to have the setting: reconciliation is True. See the document Joery sent earlier

**Comment by astirpe** [comment]
@ThijsvOers I can't find the document, could you help me?

**Comment by ThijsvOers** [comment]
@astirpe this task refers to the email Joery sent on the 22th of August, This is what he wrote on this topic:

If you mean which GL accountants should be reconciled, my answer is that de debtors, creditors and transfer accounts should be reconciled?

So all transfer accounts should be marked reconciled True

**Comment by ThijsvOers** [comment]
@astirpe Filter on all accounts that start with 1105 until 1107: these  are transfer accounts

**Comment by ThijsvOers** [comment]
Also account 1101050 and 1203050

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/475605e479427ef87c287fc3ee0709b2583d0ee0

**Comment by ThijsvOers** [comment]
tested and ok
