### ISSUE TITLE
Default accounts for early payments (debtor and vendor)

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#40]
We do not have default accounts for profit and loss regarding the early payment discountsetting

![image](https://github.com/onesteinbv/addons-container/assets/30256071/a11cc4de-d52f-43c8-929c-e21c671d9aa8)

**Comment by ThijsvOers** [comment]
@astirpe These numbers should be 7008010 and 7008020

![image](https://github.com/onesteinbv/addons-container/assets/30256071/a94149e0-a479-4038-b969-5602612c6d87)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/78f7c72892662e3f1b2d42306196ff902c62aa08

**Comment by ThijsvOers** [comment]
Tested with  a new instance and solved
