### ISSUE TITLE
No prefix

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#41]
I created in the lastes testinstance a customer invoice, tested the early payment. This works as expected but I saw that the bookings regarding the early payment do not have a prefix. These are the lines that were created with doing a manual payment,

![image](https://github.com/onesteinbv/addons-container/assets/30256071/9352d77c-2025-4fca-992e-8c70a887fff1)

**Comment by astirpe** [comment]
@ThijsvOers I can't reproduce it locally. Can we maybe try to reproduce it together?

The prefix is one of the field in the sequence of the related journal. Was the sequence modified manually?

**Comment by ThijsvOers** [comment]
@astirpe no, sentd me an invite an we can look at it togheter

**Comment by astirpe** [comment]
The prefix issue is caused by OCA module `account_move_name_sequence`.
W also had another problem with that module, regarding duplicated sequences.
Now I'm starting to doubt: do we really need this module?

**Comment by ThijsvOers** [comment]
I do not know this, is this something Andre might know?
    On Friday, September 1, 2023 at 10:29:38 AM GMT+2, Andrea Stirpe ***@***.***> wrote:  
 
 


The prefix issue is caused by OCA module account_move_name_sequence.
W also had another problem with that module, regarding duplicated sequences.
Now I'm starting to doubt: do we really need this module?

**Comment by astirpe** [comment]
Uninstalling that module, the result is this:
![Screenshot from 2023-09-01 10-37-47](https://github.com/onesteinbv/addons-container/assets/7657635/1fa4dcae-0a2c-44e0-bf70-15636cb77345)


@andreschenkels is module `account_move_name_sequence` required for a specific reason? Or can we just remove it and simplify things?

**Comment by ThijsvOers** [comment]
@astirpe @andreschenkels I have read the module info and I am not conviced that we want to deviate from the Odoo standard , This would mena uninstalling the module (and fixing the issue we have. I hope Andre can give his input, since he has more detailed knowledge of this module.

**Comment by astirpe** [comment]
Removal of `account_move_name_sequence` proposed in https://github.com/onesteinbv/addons-container/pull/44, to be merged once the decision of removing the module will be confirmed.

**Comment by ThijsvOers** [comment]
Testes and ok
