### ISSUE TITLE
Correct accounts after testing SEPA

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#42]
I have tested the SEPA flow, we need the following changes:

1.Change the type of accounts 1101050 and  1203050 to 'current assets' AND recocile is True
2. For each bank journal we need to add the 1203050 account to the tab outgoing payments (see third screenshots). We do need to do this, otherwise we have an incorrect payment status on the vendor bills.

![image](https://github.com/onesteinbv/addons-container/assets/30256071/d1ca20b2-5c2f-42c2-b1ea-18d811c7d554)
result pint 1:
![image](https://github.com/onesteinbv/addons-container/assets/30256071/7204022e-07d5-4148-a00e-9a05aa1275f3)

![image](https://github.com/onesteinbv/addons-container/assets/30256071/1c37c1f6-b080-4b41-bd11-4ae86252de65)

**Comment by ThijsvOers** [comment]
@astirpe can you also check if SEPA true false is correctly shown on the setting menu under invoicing? I am not sure if I have enabled SEPA or not 
![image](https://github.com/onesteinbv/addons-container/assets/30256071/1afcd5d6-fdc8-4d97-8ba8-94f0473698ed)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/aec382b7045f27fabdfccc137bbe62e8a8f87347

**Comment by ThijsvOers** [comment]
Tetsed and ok
