### ISSUE TITLE
Add extra rights to the (default) user

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#45]
We need the users to have access to the following usergroup, otherwise the user will not be able to add a bank number

Extra Rights/Accounting / Payments

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/3edb2c7bdfa60447824695a8ad6c154b86a31e77

**Comment by ThijsvOers** [comment]
tested on dev and on curq, ok
