### ISSUE TITLE
Install Ponto module by default

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#47]
Can the following Module be installed directly (as initial installation)? should work for all containers

Online Bank Statements: MyPont

**Comment by astirpe** [comment]
Added `account_statement_import_online_ponto` to `container_install_basis` in https://github.com/onesteinbv/addons-container/commit/6a7d4dc0e2457de950c47a71870170f1300a2cd9

**Comment by ThijsvOers** [comment]
tested and module is installed
