### ISSUE TITLE
allowed journal issue

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#49]
created a new bank,bank not copied to to the allowed journal of the suspense account

![image](https://github.com/onesteinbv/addons-container/assets/30256071/1fa7f9fa-30db-4b72-874d-0934329a962f)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/8538d394ac15a5d730ae86c74a1f162c9f5e6c81

**Comment by ThijsvOers** [comment]
@astirpe Tested on dev and ok

**Comment by ThijsvOers** [comment]
Andrea added extra functionality that on creation of a new journal this new journal is added to the allowed journal field on the all accounts where the same journal was already there. This does not work for journals with type bank&cash.

**Comment by ThijsvOers** [comment]
I will close this task since I added the comments to the correct issue
