### ISSUE TITLE
Onboarding error

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#50]
When I create a new company I see the standard odoo onboarding lint where I can check chart of account etc. If I do this, the standard COA is shown

**Comment by astirpe** [comment]
Removed onboarding step regarding COA setup, done in https://github.com/onesteinbv/addons-container/commit/0404d7be04113b0b003c71068cdf0f8cf862c0d3

**Comment by ThijsvOers** [comment]
Tested on dev and ok, I will close the issue
