### ISSUE TITLE
Dutch not default on automatic installation

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#54]
On installation the Dutch language is activated and the default language. English is also automatically activated, so the user can switch language (and use the language for customers and suppliers)

**Comment by ThijsvOers** [comment]
As a result when creating a new customer the language is not Dutch. Some of the accounting labels on the accounting dashboard are not translated (Dutch is the defasult activated language)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/b1030fbb1ff943a0bffc5531904d7b488d55a1c7

@ThijsvOers could you check if spinning up a new instance will correctly load the dutch translations?

**Comment by astirpe** [comment]
In https://github.com/onesteinbv/addons-container/commit/c38469841b7271ce6acf88341896c3a0bcca8c87 added module `partner_country_default_nl` to set default language NL when creating new customer.

**Comment by astirpe** [comment]
Translation of journals to Dutch in https://github.com/onesteinbv/addons-container/commit/3439d0c5b9a981a6a8ea5e47c658e5147511645a

**Comment by ThijsvOers** [comment]
Tested with latest update and now OK
