### ISSUE TITLE
Error in XAF export

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#58]
When I create an audit file (UNIT4 boolean is set by me to true), I get the following error. I am not sure if this is a bug or missing configuration.

line 7382: b"EntityRef: expecting ';'"

![image](https://github.com/onesteinbv/addons-container/assets/30256071/8a3f2a2c-f17c-473d-aa0d-985a692861c4)

**Comment by ThijsvOers** [comment]
@astirpe I installed a new database, I now get the following error : Element '{http://www.auditfiles.nl/XAF/3.2}generalLedger': Missing child element(s). Expected is ( {http://www.auditfiles.nl/XAF/3.2}ledgerAccount ).

**Comment by astirpe** [comment]
Fixed in https://github.com/onesteinbv/addons-oca/commit/a44666170ad4959ced80fdb8fd7721562faaae61 and proposed the fix also to OCA in https://github.com/OCA/l10n-netherlands/pull/398

**Comment by ThijsvOers** [comment]
tested and works now
