### ISSUE TITLE
MyPonto connection

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#59]
I have been able to create the correct connection with MyPonto. I have synchronised the account and initially it looked ok. But when I pulled the myponto for all statementlines for this year I only receveided back 1 statement line.

The issue is that the connection does not seem stable

**Comment by ThijsvOers** [comment]
It has something to do with the date range you give in when you are pulling in the lines. The result is not in line with the date range you apply. Fr example: I had a bankstatementline from 4-4-2023, I can only retreive this line when I use date from 3-4 until today.



![image](https://github.com/onesteinbv/addons-container/assets/30256071/b3f387e0-eb99-4b41-8ba7-510d7591711f)

**Comment by ThijsvOers** [comment]
@astirpe I have imported my statement lines from the past with on a monthly basis. I do get more lines than using the daily update option, but still not everything. For aug1th I have 3 statementlines inmy bank but the Ponto connection only imported one line.

**Comment by astirpe** [comment]
Module `account_statement_import_online`, required by the ponto connector, updated in https://github.com/onesteinbv/addons-oca/commit/a83db6e0c6f8013d52605bc322e5ab62f5cef8c0 after the latest changes from OCA

**Comment by ThijsvOers** [comment]
@astirpe Tested with actual data. I have 3 lines from august 1th which are not imported when I import the monthly statement and have a start date 1-8 03:00. The module actually looks at the time and not the date. If I fill in 01-08 00:00:00 I do get the 3 lines

**Comment by astirpe** [comment]
Should be now fixed with https://github.com/onesteinbv/addons-oca/commit/3d6d23dd49662c0b2702b7a3f15280f2be5f5298

**Comment by ThijsvOers** [comment]
@astirpe great, please let me know when I can test this fix on my Curq instance

**Comment by ThijsvOers** [comment]
@astirpe I did a complete test with all the 3 options (daily, weekly and monthly statements) and in all three cases all bank statement lines are now imported. I think this is a great new feature for Curq and I do think quite a lot of other Odoo community users will be happy that we fixed the issues to make this app work properly.
