### ISSUE TITLE
Journal check chronology

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#60]
Default value for boolean 'check chronology' should be set to 'True'

![image](https://github.com/onesteinbv/addons-container/assets/30256071/432e0173-fa3a-4bea-a1ce-dff6a93bce39)

**Comment by ThijsvOers** [comment]
the checkbox makes sure that you validate in the correct order
@astirpe after dscussion with Richard it's been decided that we want the value for this checkbox to be set to True.

**Comment by astirpe** [comment]
@ThijsvOers For both sale and purchases?

**Comment by astirpe** [comment]
Done for purchase only in https://github.com/onesteinbv/addons-container/commit/5d66e37bf5e7ed428aa92a68d36fb77aa32935ce

**Comment by ThijsvOers** [comment]
Tested and it's default true for vendor bills
