### ISSUE TITLE
Create fiscal year for current year

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#61]
In order to get the cronjob that creates new fiscal years working we need on installation of a new databse the creation of the first fiscal year. This should by default be the 1th of January of the current year until the last day of the current year 31th december (31th should be included in this current year)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/047ce908dda4ecd0086cc8708e3238c20e21ca21

**Comment by ThijsvOers** [comment]
Tested and the first Fiscal year is created (defaul 1-1 until 31-12, this can be changed). Next years will automatically be created in due time (there is a cron job for this)
