### ISSUE TITLE
error on upload first vendor bill

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#64]
When you create a new DB and want to upload your first document you will get an error if you want to preview an example. If you contiue and upload your own document there is no issue anymore
![Error vendor bills](https://github.com/onesteinbv/addons-container/assets/30256071/deb7bc21-7de9-40bf-b525-2b61ccbd3450)

**Comment by astirpe** [comment]
I can't reproduce it locally, it seems something more related to the server

**Comment by astirpe** [comment]
Removed onboarding "Import your first bill" popup in https://github.com/onesteinbv/addons-container/commit/d69c4ff7a76b0ce2647f3c059dcd8afe0a1ac12b

**Comment by ThijsvOers** [comment]
tested with latest version and solved
