### ISSUE TITLE
Show only active accounts on financial reports

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#69]
When I create a MIS P/L or Balance report and uncheck the option 'hide accounts with amount'tehn I will get all accounts included the inactive accounts. Can we only show active accounts in this case?

![image](https://github.com/onesteinbv/addons-container/assets/30256071/033c48e4-81eb-48e4-a0a8-a01672c03003)

**Comment by astirpe** [comment]
@ThijsvOers hiding inactive accounts, that have a non-zero amount, doesn't seem correct to me. Setting an account to inactive is meant to avoid that account be used further. But if that account was already used previously, it should appear in the report anyway.

Checking the code in the module (is not the MIS report module but is the OCA account_financial_report module) seems not an easy implementation.

**Comment by ThijsvOers** [comment]
@astirpe If this is not an easy fix, then we should forget it for now
