### ISSUE TITLE
Small change to accountname 0506010 Niet verdeelde winst onverdeelde winst

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#70]
PLease remove part 'onverdeelde winst' from accpunt 0506010

![image](https://github.com/onesteinbv/addons-container/assets/30256071/62c02a28-c6a1-4bd3-a467-e4eb0cbfbe7d)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/f01991ee9e2a4600bc2606ea2370f08715f248cb

**Comment by ThijsvOers** [comment]
Tested and ok
