### ISSUE TITLE
Change description 

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#71]
For some account groups the short description is the better option than showing the full description in field 'name'. We want to change the description of the following groups:

40
42
43
71

Example: 

![image](https://github.com/onesteinbv/addons-container/assets/30256071/4589b44d-72a7-4860-ba71-aad072848023)

**Comment by astirpe** [comment]
@ThijsvOers is it something you can do yourself by editing this file? https://github.com/onesteinbv/addons-container/blob/16.0/l10n_nl_rgs/data/account.account.template.csv

**Comment by ThijsvOers** [comment]
@astirpe I want to do this, can I do it by export and then import the data?

**Comment by astirpe** [comment]
@ThijsvOers it's the csv file that should be edited

**Comment by ThijsvOers** [comment]
tested and ok

**Comment by ThijsvOers** [comment]
I closed the wrong task

**Comment by ThijsvOers** [comment]
I have done the chages in the csv (and also checked other accounts). Ruud will do an extra test

**Comment by ThijsvOers** [comment]
@astirpe I have changed quite some extra descriptions, can you restart Jenkins tomorrow (YW is still testing today)? I will close the is issue for now
