### ISSUE TITLE
Incorrect MIS report p/l

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#72]
The following accounts are missing in the MIS report

8011100 | Opbrengsten servicecontracten
8012100 | Lasten servicecontracten
8014100 | Lasten verhuur en beheeractiviteiten
8015100 | Lasten onderhoudsactiviteiten
8016100 | Overige directe operationele lasten explotatie bezit
8030100 | Verkoopopbrengst vastgoedportefeuille
8032100 | Boekwaarde verkochte vastgoedportefeuille
8033100 | Verkoopkosten
8040100 | Overige waardeveranderingen van vastgoedportefeuille
8050100 | Opbrengsten overige activiteiten
8051100 | Kosten overige activiteiten

**Comment by astirpe** [comment]
Do they miss in the Profit Loss ?

**Comment by ThijsvOers** [comment]
@astirpe yes in the MIS P/L

**Comment by astirpe** [comment]
@ThijsvOers shall those accounts appear under the "Netto-omzet" section of the MIS P/L?

Here is the mapping with the groups:

| Account | Account Name                                          | Group   | KPI Name | Value type | Expression                               |
| ------- | ----------------------------------------------------- | ------- | -------- | ---------- | ---------------------------------------- |
| 8011100 | Opbrengsten servicecontracten                         | 8011000 | nl_80_11 | Numeric    | -balp[('group_id.code', '=', '8011000')] |
| 8012100 | Lasten servicecontracten                              | 8012000 | nl_80_12 | Numeric    | -balp[('group_id.code', '=', '8012000')] |
| 8014100 | Lasten verhuur en beheeractiviteiten                  | 8014000 | nl_80_14 | Numeric    | -balp[('group_id.code', '=', '8014000')] |
| 8015100 | Lasten onderhoudsactiviteiten                         | 8015000 | nl_80_15 | Numeric    | -balp[('group_id.code', '=', '8015000')] |
| 8016100 | Overige directe operationele lasten explotatie bezit  | 8016000 | nl_80_16 | Numeric    | -balp[('group_id.code', '=', '8016000')] |
| 8030100 | Verkoopopbrengst vastgoedportefeuille                 | 8030000 | nl_80_30 | Numeric    | -balp[('group_id.code', '=', '8030000')] |
| 8032100 | Boekwaarde verkochte vastgoedportefeuille             | 8032000 | nl_80_32 | Numeric    | -balp[('group_id.code', '=', '8032000')] |
| 8033100 | Verkoopkosten                                         | 8033000 | nl_80_33 | Numeric    | -balp[('group_id.code', '=', '8033000')] |
| 8040100 | Overige waardeveranderingen van vastgoedportefeuille  | 8040000 | nl_80_40 | Numeric    | -balp[('group_id.code', '=', '8040000')] |
| 8050100 | Opbrengsten overige activiteiten                      | 8050000 | nl_80_50 | Numeric    | -balp[('group_id.code', '=', '8050000')] |
| 8051100 | Kosten overige activiteiten                           | 8051000 | nl_80_51 | Numeric    | -balp[('group_id.code', '=', '8051000')] |


CC @yung-wang

**Comment by astirpe** [comment]
Is this ok or should be grouped in a different way?


![Screenshot from 2023-10-05 10-12-20](https://github.com/onesteinbv/addons-container/assets/7657635/53ea9e21-c1c9-4d5c-8bfc-930fa1ec23e9)


Changes tracked here: https://github.com/onesteinbv/addons-container/pull/73

**Comment by ThijsvOers** [comment]
@astirpe how can I test this change? is the change applied to the current Curq databases? TIA

**Comment by astirpe** [comment]
@ThijsvOers I merged the PR and start the jenkins. You will be able to test it in 30 min

**Comment by ThijsvOers** [comment]
Tested with an import of all accounts, and all accounts are in the P/L
