### ISSUE TITLE
Type incorrect for some account

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#74]
Ruud raised the following remark regarding group starting with 1103,the Type of the group should be changed. 

1103xxx: Group 'Current liablities' should be 'Current assets' (as in the standard Dutch Odoo account scheme)

**Comment by ThijsvOers** [comment]
@astirpe this request is validated by Jouery, can you do the change (type of all accounts in Group 1103xxx should be 'current assets'instead of 'current liablities'.

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/5eb6d0af0c8ca9f1182e53ec9140215300271fa7

**Comment by ThijsvOers** [comment]
Tested and ok
