### ISSUE TITLE
Incorrect fields on customer info

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#75]
On the customer invoice as a default I see the payment reference field 2 times (a dropdown and a textfield) and also a field payment mode (with no info). In standard Odoo I see only one payment reference field (textfield). Why do we need the Payment Mode field and payment rerence field with the dropdown. These fields are related to the Direct Debit module. If the customer does not use this option, the fields should not be visible

![image](https://github.com/onesteinbv/addons-container/assets/30256071/6a33a89d-c63b-455c-8664-fd92f7a39df9)

**Comment by ThijsvOers** [comment]
@astirpe The direct debit functionality is working (i have tested this with a valid direct debit issuer account), but I think we should only make these fields visible once the settings is activated in the settings menu(screenshot). Please also keep in mind that these fields are also in use for vendor bills.
![image](https://github.com/onesteinbv/addons-container/assets/30256071/68031525-89d3-45cf-b1ea-45e9a2ece818)
![image](https://github.com/onesteinbv/addons-container/assets/30256071/bc8d845d-551c-4bcd-84f5-7edeafd53465)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/7d3ea351303fef0cf7ab628d36342ed7343e193b

**Comment by ThijsvOers** [comment]
@astirpe Can you update everything (Jenkins etc) today? I can then test my other changes as well (description of account names). TIA

**Comment by astirpe** [comment]
@ThijsvOers done

**Comment by ThijsvOers** [comment]
@astirpe I have tested the task and I have one remark (which I should have medtioned earlier): this restriction is only applicable for Customer invoices, not for Vendor bills (for the vendor billl the field payment_mode_id is always visible)

**Comment by astirpe** [comment]
Fixed in https://github.com/onesteinbv/addons-container/commit/6716934dd03ddb6296f08ed23bf9970a87ddc1fe

**Comment by ThijsvOers** [comment]
Tested and ok, I can see the difference between customer invoice and vendor bill
