### ISSUE TITLE
Automatically created accounts by Odoo

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#76]
Bank suspense account and Liquidity Transfer are created automatically by Odoo, they are not part of the RGS. The Liquidity account can go to RGS account 1003010
Bank suspense account has no equivalant, but for this account the option 'Reconcile' should be set to True

To do: 
1. connect Liquidity account Odoo to RGS account 1003010
2. Bank suspense account: Reconcile=True

**Comment by astirpe** [comment]
Done:
- liquidity: https://github.com/onesteinbv/addons-container/commit/fe109e2a23f625fc818e6d176e7abf723f202c40 and https://github.com/onesteinbv/addons-container/commit/94ba8d2e20a9c948098b34f682105eed73bfafcf
- suspense: https://github.com/onesteinbv/addons-container/commit/efce9a6ecbefff919736b7d6d486aa198a1fa553

**Comment by ThijsvOers** [comment]
@astirpe tested and ok, I will close the task
