### ISSUE TITLE
Total residual not translated in account_invoice_overdue_reminder

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#77]
In https://github.com/OCA/credit-control/blob/16.0/account_invoice_overdue_reminder/i18n/nl.po There is one field that is not translated, but this is because it's not in the list of translatable items.

The translation should be: 'Totaal openstaand bedrag"

![image](https://github.com/onesteinbv/addons-container/assets/30256071/eb803a20-40bd-4b93-b4a9-d012922c2005)

**Comment by astirpe** [comment]
Should be translated in here:
https://github.com/OCA/credit-control/blob/16.0/account_invoice_overdue_reminder/i18n/nl.po#L251

@Jan-Onestein

**Comment by ThijsvOers** [comment]
will close this task for now, Jan added the text
