### ISSUE TITLE
Currency symbol

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#78]
Since the default language on installation is English, on the EUR currency the value for showing the value is 'after the amount'. Can you change that to 'before the amount'?

![image](https://github.com/onesteinbv/addons-container/assets/30256071/0497bb5c-eae1-45b7-ad0f-2cfa797b35bc)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/8d261685702fd492fa7e54e220c3e35c05b8140d

**Comment by ThijsvOers** [comment]
Tested and ok
