### ISSUE TITLE
Do not allow creation of bank journal on menu Journals

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#79]
Since we have implemented the automatic creation of bankjournals from menu 'add bank account under the config menu, we should prevent the creation in menu Journals (user will get into all sorts of issues). Editing is still possible.

User should get a message "please add your bank number in menu  'add bank account'. 

![image](https://github.com/onesteinbv/addons-container/assets/30256071/32138526-76e7-4cb4-8590-bbd11990adf8)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/8ed229025cd7683d6a1b7061e2df3ed8575abc7b

**Comment by ThijsvOers** [comment]
Tested and OK
