### ISSUE TITLE
RGS: error on validating a customer invoice

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#8]
When adding an invoice line to a customer invoice, an error occurs when validating the invoice.
After investigations, the root of the problem is the wrong "Account Receivable" and "Account Payable" values that a set on the contact when creating a new customer:

![image](https://github.com/onesteinbv/addons-container/assets/7657635/cff03680-fcad-4485-80b1-c7f2ca6bea11)

**Comment by astirpe** [comment]
Fixed with https://github.com/onesteinbv/addons-container/commit/0e400e5b36be12e88717262db0abd144941514f5

**Comment by andreschenkels** [comment]
@astirpe did you also do this on v15 or is v15 absolete?

**Comment by astirpe** [comment]
I will backport everything to V15. I didn't do yet because I was focusing on V16 only, since they are going to setup a testing instance with V16.
If you have anything to commit on V15 or V16, please do. I will take care of porting or backporting all the stuff.
