### ISSUE TITLE
Set verify VAT to true

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#81]
-Verify VAT Numbers is not marked, please set the value to True

![image](https://github.com/onesteinbv/addons-container/assets/30256071/67b764ca-3ee9-4da1-bf0e-1777c526f6e5)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/bbc402e6bad4eefbdf02529ade833444fcd53ea7

**Comment by ThijsvOers** [comment]
Tested and ok
