### ISSUE TITLE
Add Direct debit in payment mode

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#82]
We have Direct debit as payment method, but we need direct debit as payment mode as well.

I have added the default values in the second screenshot

![image](https://github.com/onesteinbv/addons-container/assets/30256071/df649db3-0f92-4dd2-b7e4-66b6dcecdea9)

![image](https://github.com/onesteinbv/addons-container/assets/30256071/7bd1f69f-9b51-4341-b4be-779a75d0e84d)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/bf64780aad11b45b035a62bfecee47845e50ae5b

**Comment by ThijsvOers** [comment]
Tested and ok
