### ISSUE TITLE
Translate Activa profile menu item

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#84]
In Dutch we have 2 times menu Activa Categorie, where in English we see a group asset profiles and a group asset Groups.

Pleas translate Asset profiles to 'Activa profielen'.

![image](https://github.com/onesteinbv/addons-container/assets/30256071/e078fa83-7c24-4b2b-b42d-40982f13b4da)
![image](https://github.com/onesteinbv/addons-container/assets/30256071/77732c0d-fd58-441e-ab26-084bdcc866b0)

**Comment by astirpe** [comment]
Done in internal repository https://github.com/onesteinbv/addons-oca/commit/727f4623de9711d57bc3fd8798d6b3538236aadd

Still to be done in OCA repository.

**Comment by ThijsvOers** [comment]
Tetsed and ok, to be translated in OCA
