### ISSUE TITLE
translation of Manualy Invoice Purchase/Sale  Contracts incorrrect

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#85]
Menu in Customers/Vendors is not really straightforward with same names coming up. Most of this is due to incorrect Translations like: Manualy Invoice Purchase Contracts is translated as: "Inkoop contracten". But there already is an "Inkoopcontracten".
Manualy Invoice Sale Contracts is translated as: "verkoop contracten". But there already is a "Verkoopcontracten".

![image](https://github.com/onesteinbv/addons-container/assets/30256071/ab31e7a2-7ac6-4c52-b9d3-3d622aadb836)
![image](https://github.com/onesteinbv/addons-container/assets/30256071/9076d7f3-3364-4178-b5a1-fe4e90132441)

**Comment by astirpe** [comment]
Done in internal repository https://github.com/onesteinbv/addons-oca/commit/470e2b3b3a41a1fa5ae5818f2d5863b3d3d6ad37

To be done in OCA repository.

**Comment by astirpe** [comment]
Extra fix: https://github.com/onesteinbv/addons-oca/commit/82e338483ec7974127d87208d29f10bd3eaf7521

**Comment by ThijsvOers** [comment]
I translated the oca module, now we have to wait for the changes to be implemented by oca
