### ISSUE TITLE
allowed journal additions

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#86]
Since we have a specific standard miscellaneous journal for deferred revenues, we need this journal (accruals) as allowed in a range of specific accounts (see text, GL range is 4, 7 and 8 +type= 'vooruitberaling')) Vooruitbetaling= prepayments
 
****
Allowed journal is blocking the creation of the deferred entries. For now FIXED in fid-finance-curq environment. Need fix in Code later. Every GL (in 4, 7, 8) linked to klantfacturen and leveranciersfacturen, I added the overlopende kosten journal (accruals) to allowed journal. I also did the ones with type ‘vooruitbetaling’ (prepayments).

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/609680325de0e89e5da37df0fae58d405975175e

**Comment by ThijsvOers** [comment]
tested and ok
