### ISSUE TITLE
SEPA module OCA not working correctly with standard Odoo payment

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#87]
In Curq we implemented OCA module account_banking_sepa_credit_transfer. This module conflicted with standard Odoo functionality regarding payments (e.g when doing a SEPA payment the payment status of the vendorbill becomes 'paid' instead of 'in payment')

There is a refactoring done for the OCA module in PR https://github.com/OCA/bank-payment/pull/1174. Biggest change in the PR is that the payment status for 'odoo payments' is 'in payment' again.

Since this PR is not done, we do not want to merge it into Curq production, hence Jan created a standalone server with all curq modules and with this PR. I have tested the module and in our Cirq setup the payment status stays on 'paid',  It looks like the PR is not working on Curq

Testenvironment Jan: http://odoo16ce.onestein.lan:8069/web (you have to add 10.11.1.229 odoo16ce.onestein.lan into your host file)

**Comment by alexis-via** [comment]
What is Curq ?

**Comment by ThijsvOers** [comment]
Curq is an open source Saas platform based on Odoo 16 CE with extra OCA modules. The platform aims for (Dutch) companies who want to work with a 100% open source Odoo version. We will provide hosting and also extra applications like Nextcloud. This platform will be launched in the first halve of next year.
