### ISSUE TITLE
Extra default filter for menu chart if accounts

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#89]
Joery request an extra default filter on menu chart of accounts 
![image](https://github.com/onesteinbv/addons-container/assets/30256071/63602731-8976-4d89-81db-277ee4a0d082)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/d45d8fa7252aaa38812c116f90e842a9288e71fe

**Comment by ThijsvOers** [comment]
tested and ok

**Comment by ThijsvOers** [comment]
@bvanjeelharia Anjeel, is it possible to add an extra ordering to this filter? customer requests to order the groups in a numerical order
![image](https://github.com/onesteinbv/addons-container/assets/30256071/7a0c1a50-93e8-4c93-818d-84573a9dc538)

**Comment by ThijsvOers** [comment]
@andreschenkels Andre, I do not want to request any changes without your advice (this comment is regarding my extra comment on the extra ordering). Anjeel checked if it's possible to add an extra ordering, but this would have impact on other menus.  Can you check if the request can be done (ordering based on the subgroups, in the screenshot you see that the ordering is not numerical). I suspect there are some issues which prevents an easy ordering.

**Comment by andreschenkels** [comment]
I'll check it could be it's ordered on id

**Comment by bvanjeelharia** [comment]
@andreschenkels , currently its ordered based on sort_code(Sorting Code), code(Referentiecode), code_prefix_start(Code Prefix Start)

**Comment by andreschenkels** [comment]
I think it should be: sorting_code, display_name (if this exists in account.group)

**Comment by ByteMeAsap** [comment]
Fixed with https://github.com/onesteinbv/addons-generic/pull/41
