### ISSUE TITLE
RGS: fiscal position for EU landen

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#9]
The fiscal position in case of exporting to EU is not always correctly computed.
It's because the definition of [EU landen](https://github.com/onesteinbv/addons-container/blob/16.0/l10n_nl_rgs/data/account_fiscal_position_template.xml#L19) says `vat_required=True`.

To reproduce the problem:

- Create a "customer BE" having country=Belgium, do not set any value in VAT field
- Create an invoice for "customer BE"
- Add a line in the invoice: the tax is wrong (buiten EU)

To fix it in the code (RGS module) I'm thinking to adopt the same logic as standard odoo does: defining an extra fiscal position, named "EU landen privaat", that is the same as "EU landen" but is set with `vat_required=False`.

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/136a90226c414cb4b1eb19a53e4e8c0eb99d4903

**Comment by ThijsvOers** [comment]
@astirpe Andrea, there is a problem for Dutch companies/customers in the situation that there is no VAT registered and you create a new product on the invoiceline: The incorrect VAT europe tax is used
Once you have saved the product and fill the product in a new invoice (for the same customer), the VAT is added correctly

**Comment by astirpe** [comment]
@ThijsvOers fixed with https://github.com/onesteinbv/addons-container/commit/2f1223b34f9a5ca515d727ff6b150bdf9ccd80f2 where I added a fiscal position "Binnenland B2C". Let me know if that's ok.

**Comment by ThijsvOers** [comment]
@astirpe tested the latest fremark regarding the VAT fpor new products and it's ok now. I will close the issue
