### ISSUE TITLE
disable analytic account by default

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#90]
request is to disable the analytic account option in teh settings (it's now set to 'true'

![image](https://github.com/onesteinbv/addons-container/assets/30256071/0be94dba-2360-46ac-a142-7ff394fcb121)

**Comment by espo-tony** [comment]
@ThijsvOers 
In module l10n_nl_rgs_usability , the group "Analytic Accounting" (this flag is kind of a mirror that says if said group is set on the user) was set by default on all Internal Users. I removed it (of course, this won't disable it from all users who already have it), as for your request.

**Comment by ThijsvOers** [comment]
Tested on latest instance and ok
