### ISSUE TITLE
Disable option Automatic Currency Rates (OCA)

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#91]
- disable module exchange rate in the settings

![image](https://github.com/onesteinbv/addons-container/assets/30256071/3ec53f36-a744-4239-8492-a796fc818dc7)

**Comment by espo-tony** [comment]
@ThijsvOers 
Done in new module 'account_configuration' (you'll need to install it).
Please, notice that because this field is introduced in a different module, and already set to True, I was forced to add a mechanism to update the field on all already existing records upon module installation.

**Comment by ThijsvOers** [comment]
Tested on latest instance and ok
