### ISSUE TITLE
Change default Check chronology on Journals

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#92]
The settings for the customer invoice and vendorbill journal should be switched:

Vendorbill: setting goes from True to False
Customer invoice: setting geos from False to True

Example for customer invoice:
![image](https://github.com/onesteinbv/addons-container/assets/30256071/41d2e08b-a85d-4d2c-b6d8-d2a39bce12aa)

**Comment by espo-tony** [comment]
@ThijsvOers 
Done in new module 'account_configuration' (you'll need to install it).
Please, notice that because this field is introduced in a different module, and already set to False, I was forced to add a mechanism to update the field on all already existing records upon module installation.

**Comment by ThijsvOers** [comment]
@espo-tony I have just tested this task on a new instance and the chronology on customer invoice is default True (this is correct), but the default value for journal 'vendorbill'is not set to False as requested.

**Comment by espo-tony** [comment]
@ThijsvOers 
I think I fixed it. Can you check?

**Comment by ThijsvOers** [comment]
@espo-tony Hi Antonio, I just checked with a new instance and there is no change: Vendorbill is still True and Customer invoice is still False. Could you check? TIA

**Comment by espo-tony** [comment]
@ThijsvOers 
I just verified on a local instance.
When journal type is Sale, Check Chronology goes to True.
When journal type is Purchase, Check Chronology goes to False.

If this is not what was expected, or if you don't experience the same, please let's have a quick call tomorrow to settle this up and understand what's wrong.

**Comment by ThijsvOers** [comment]
@espo-tony how it works with you localally is the correct way. Yesterday I created a new instance in the Curq environment and on that instance the settings were the old ones. Can it be that your chance is not submitted somehow? 
To be sure: True means that I see a check and false that the value is not set and i don't see a check?

**Comment by espo-tony** [comment]
@ThijsvOers 
Yes, indeed. True you see a check, False you don't.
I also checked if I forgot to push it, but no: the commit is there: https://github.com/onesteinbv/addons-container/commit/b6587d3e06ed02bd3ba7f6e7c78e88631e6853c6

Let me know if you want us to take a look together into a live instance.

**Comment by ThijsvOers** [comment]
I will check again next week, this is not a priority for now
have good weekend
    On Friday, December 8, 2023 at 12:13:33 PM GMT+1, Antonio Esposito ***@***.***> wrote:  
 
 


@ThijsvOers
Yes, indeed. True you see a check, False you don't.
I also checked if I forgot to push it, but no: the commit is there: b6587d3

Let me know if you want us to take a look together into a live instance.

**Comment by ThijsvOers** [comment]
I just created a new company in the lastest test instance and the settings were correct. I will close the task
