### ISSUE TITLE
Changes in defaults asset profile menu

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#93]
Some changes were made to the examples of menu 'asset profiles. Pleas add the changes to the standard dataset

Before:
![image](https://github.com/onesteinbv/addons-container/assets/30256071/cea2ccc3-3618-483d-accf-df1890e45718)
After  the changes
Changes in column 'number of years' and 'prorata'

![image](https://github.com/onesteinbv/addons-container/assets/30256071/62ccaf57-69a9-4671-852e-69536e6c77c7)

**Comment by ThijsvOers** [comment]
checked and ok

**Comment by ThijsvOers** [comment]
@bvanjeelharia I installed a new instance yesterday, the number of years for the asset profiles were changed correctly, but the prorata boolean was false (should be true). I did test this earlier and then the value was true. Can you check if the change was done correctly? TIA

**Comment by bvanjeelharia** [comment]
@ThijsvOers , this should be fixed with the latest change

**Comment by ThijsvOers** [comment]
checked and solved
