### ISSUE TITLE
Extra default filter on reconcile widget

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#94]
On the reconcile widget I see all accounts when I go to the tab 'manual operation'. We want to have an extra default filter (account is active' (see screenshot 2), currently all accounts are shown (archived ones as well)

![image](https://github.com/onesteinbv/addons-container/assets/30256071/95ef34bf-b29b-4ac1-9bc3-424c3ef9d825)

![image](https://github.com/onesteinbv/addons-container/assets/30256071/3f4cfa0c-d25c-4ed4-a3aa-77e200b933e0)

**Comment by ThijsvOers** [comment]
@bvanjeelharia you can work on this task

**Comment by bvanjeelharia** [comment]
@ThijsvOers , I have added domain on Account field to show only current company, non deprecated and non 'Bank and Cash' or 'Off-Balance Sheet' accounts

**Comment by ThijsvOers** [comment]
tested and ok
