### ISSUE TITLE
Description Fiscal position labels

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#95]
We need some small changes to the description of 2 fiscal positions 
before

![image](https://github.com/onesteinbv/addons-container/assets/30256071/f88a99e0-106a-401e-8c3a-175f17dcb648)

after

![image](https://github.com/onesteinbv/addons-container/assets/30256071/fed1a80a-01ea-44cc-9930-582170c6f934)

**Comment by ThijsvOers** [comment]
@bvanjeelharia let me know if you need help with the translation of the textlabels

**Comment by bvanjeelharia** [comment]
@ThijsvOers , I have updated the labels for the fiscal positions as suggested

**Comment by ThijsvOers** [comment]
checked and ok
