### ISSUE TITLE
Reconciliation of partial payment

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#99]
Case: we have a bankstatementline with amount and partner, and also open invoices for this partner. We reconcile the bankstatementline  with a partial payment and want to use a reconcile model for the rest of the open amount. I cannot do this, once I click on the model my debtor or creditor amount is goen. In Enterprise it will use only the open amount for reconciliation.

![image](https://github.com/onesteinbv/addons-container/assets/30256071/44c5be70-ec2c-483f-a30c-ceeb6f4453e0)

**Comment by bvanjeelharia** [comment]
@ThijsvOers , this is contradicting with this issue - https://github.com/onesteinbv/addons-container/issues/96 as when the system was auto assigning partial payments, it wasn't fine with you
